#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

#REMOVEME? ynh_clean_setup () {
	true
}
# Exit if an error occurs during the execution of the script
#REMOVEME? ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

#REMOVEME? domain=$YNH_APP_ARG_DOMAIN
#REMOVEME? path=$YNH_APP_ARG_PATH
#REMOVEME? is_public=$YNH_APP_ARG_IS_PUBLIC
#REMOVEME? admin=$YNH_APP_ARG_ADMIN

#REMOVEME? app=$YNH_APP_INSTANCE_NAME
fpm_footprint="low"
fpm_free_footprint=0
fpm_usage="low"

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
#REMOVEME? ynh_script_progression --message="Validating installation parameters..." --weight=1

#REMOVEME? install_dir=/var/www/$app
#REMOVEME? test ! -e "$install_dir" || ynh_die --message="This path already contains a folder"

# Register (book) web path
#REMOVEME? ynh_webpath_register --app=$app --domain=$domain --path=$path

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
#REMOVEME? ynh_script_progression --message="Storing installation settings..." --weight=1

#REMOVEME? ynh_app_setting_set --app=$app --key=domain --value=$domain
#REMOVEME? ynh_app_setting_set --app=$app --key=path --value=$path
#REMOVEME? ynh_app_setting_set --app=$app --key=admin --value=$admin
ynh_app_setting_set --app=$app --key=fpm_footprint --value=$fpm_footprint
ynh_app_setting_set --app=$app --key=fpm_free_footprint --value=$fpm_free_footprint
ynh_app_setting_set --app=$app --key=fpm_usage --value=$fpm_usage

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression --message="Installing dependencies..." --weight=1

#REMOVEME? ynh_install_app_dependencies $pkg_dependencies

#=================================================
# CREATE DEDICATED USER
#=================================================
#REMOVEME? ynh_script_progression --message="Configuring system user..." --weight=2

# Create a system user
#REMOVEME? ynh_system_user_create --username=$app --home_dir="$install_dir"

#=================================================
# CREATE A MYSQL DATABASE
#=================================================
#REMOVEME? ynh_script_progression --message="Creating a MySQL database..." --weight=1

#REMOVEME? db_name=$(ynh_sanitize_dbid --db_name=$app)
#REMOVEME? db_user=$db_name
#REMOVEME? ynh_app_setting_set --app=$app --key=db_name --value=$db_name
#REMOVEME? ynh_mysql_setup_db --db_user=$db_user --db_name=$db_name

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

#REMOVEME? ynh_app_setting_set --app=$app --key=install_dir --value=$install_dir
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=$fpm_usage --footprint=$fpm_footprint
#REMOVEME? phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=4

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# SETUP SQL CREDENTIALS
#=================================================

ynh_add_config --template="../conf/common.php" --destination="$install_dir/protected/config/common.php"

#=================================================
# DEACTIVATE DEBUG MODE
#=================================================

ynh_replace_string --match_string="defined('YII_DEBUG') or define('YII_DEBUG', true);"\
 --replace_string="// defined('YII_DEBUG') or define('YII_DEBUG', true);"\
 --target_file="$install_dir/index.php"
ynh_replace_string --match_string="defined('YII_ENV') or define('YII_ENV', 'dev');"\
 --replace_string="// defined('YII_ENV') or define('YII_ENV', 'dev');"\
 --target_file="$install_dir/index.php"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================

# Set right permissions for curl install
chown -R $app: $install_dir

# Set the app as temporarily public for curl call
ynh_script_progression --message="Configuring SSOwat..." --weight=30
# Making the app public for curl
#REMOVEME? ynh_permission_update --permission="main" --add="visitors"
# Reload SSOwat config
yunohost app ssowatconf

# Reload NGINX
#REMOVEME? ynh_systemd_action --service_name=nginx --action=reload

# Installation with curl
ynh_script_progression --message="Finalizing installation..." --weight=2

install_sso

pushd $install_dir/protected
	php$phpversion yii migrate/up --includeModuleMigrations=1 --interactive=0

	php$phpversion yii settings/set ldap enabled '1'
	php$phpversion yii settings/set ldap hostname 'localhost'
	php$phpversion yii settings/set ldap port 389
	php$phpversion yii settings/set ldap encryption ''
	php$phpversion yii settings/set ldap username ''
	php$phpversion yii settings/set ldap password ''
	php$phpversion yii settings/set ldap baseDn 'ou=users,dc=yunohost,dc=org'
	php$phpversion yii settings/set ldap loginFilter '(uid=%s)'
	php$phpversion yii settings/set ldap userFilter 'objectClass=mailAccount'
	php$phpversion yii settings/set ldap emailAttribute 'mail'
	php$phpversion yii settings/set ldap usernameAttribute 'uid'
	php$phpversion yii settings/set ldap idAttribute 'uid'
	php$phpversion yii settings/set ldap refreshUsers '1'
	php$phpversion yii settings/set ldap refreshUsers '1'

	php$phpversion yii ldap/sync
	php$phpversion yii user/make-admin ${admin}

	ynh_local_curl "/index.php?r=installer/index/go"

	local_curl_csrf "/index.php?r=installer/config/basic" \
		"ConfigBasicForm[name]=YunoHost"

	local_curl_csrf "/index.php?r=installer/config/use-case" \
		"UseCaseForm[useCase]=" \
		"UseCaseForm[useCase]=other"

	local_curl_csrf "/index.php?r=installer/config/sample-data" \
		"SampleDataForm[sampleData]=0"

	php$phpversion yii settings/set user auth.anonymousRegistration '0'
	php$phpversion yii settings/set user auth.allowGuestAccess '0'
	php$phpversion yii settings/set user auth.internalUsersCanInvite '0'

	php$phpversion yii module/enable auth-basic

popd

# Remove the public access
#REMOVEME? ynh_permission_update --permission="main" --remove="visitors"

ynh_store_file_checksum --file="$install_dir/protected/config/common.php"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SETUP CRON CONFIGURATION
#=================================================
ynh_script_progression --message="Setuping crontab..." --weight=1

ynh_add_config --template="../conf/cron" --destination="/etc/cron.d/${app}"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP SSOWAT
#=================================================
#REMOVEME? ynh_script_progression --message="Configuring permissions..." --weight=2

# Make app public if necessary
#REMOVEME? if [ $is_public -eq 1 ]
then
	# Everyone can access the app.
	# The "main" permission is automatically created before the install script.
#REMOVEME? 	ynh_permission_update --permission="main" --add="visitors"
fi

#=================================================
# RELOAD NGINX
#=================================================
#REMOVEME? ynh_script_progression --message="Reloading NGINX web server..." --weight=2

#REMOVEME? ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
