#!/bin/bash
set -u

app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
	source /usr/share/yunohost/helpers

# Retrieve app settings
	domain=$(ynh_app_setting_get "$app" domain)

# Remove sources
	sudo rm -rf /var/www/$app
	sudo rm -f /etc/cron.d/$app

# Remove nginx configuration file
	sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Remove PHP-FPM configuration file
	sudo rm -f /etc/php5/fpm/pool.d/$app.conf

# MySQL
	dbname=$app
	dbuser=$app
	ynh_mysql_drop_db "$dbname" || true
	ynh_mysql_drop_user "$dbuser" || true

# Reload services
	sudo service php5-fpm reload
	sudo service nginx reload
