#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=1G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# Deactivate cron jobs
ynh_safe_rm "/etc/cron.d/$app"

ynh_script_progression "Upgrading source files..."

# Backup user contents
mv "$install_dir" "$install_dir.old"

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

# Restore user contents
cp -a "$install_dir.old/uploads/." "$install_dir/uploads/."
cp -a "$install_dir.old/protected/runtime" "$install_dir/protected/runtime"
cp -a "$install_dir.old/protected/config/." "$install_dir/protected/config/"
cp -a "$install_dir.old/protected/modules/." "$install_dir/protected/modules/"
cp -a "$install_dir.old/themes/." "$install_dir/themes/"

# Delete old source
ynh_safe_rm "$install_dir.old"

#=================================================
# CONFIGURE NGINX
#=================================================

ynh_config_add_nginx

#=================================================
# DEACTIVATE DEBUG MODE
#=================================================

ynh_replace --match="defined('YII_DEBUG') or define('YII_DEBUG', true);"\
 --replace="// defined('YII_DEBUG') or define('YII_DEBUG', true);"\
 --file="$install_dir/index.php"
ynh_replace --match="defined('YII_ENV') or define('YII_ENV', 'dev');"\
 --replace="// defined('YII_ENV') or define('YII_ENV', 'dev');"\
 --file="$install_dir/index.php"

#=================================================
# SETUP APPLICATION
#=================================================

ynh_script_progression "Setuping application..."

if [[ ! -d $install_dir/$HUMHUB_AUTH_BASIC_PATH ]]; then
	install_sso

	# Fix from not released https://github.com/smart4life/humhub-auth-basic/pull/7/files
	ynh_config_add --template="common.php" --destination="$install_dir/protected/modules/auth-basic/Events.php" 
	
	pushd $install_dir/protected
		php$php_version yii module/enable auth-basic
	popd
else
	current_version=$(cat $install_dir/$HUMHUB_AUTH_BASIC_PATH/module.json | jq -j '.version')
	if [ "$current_version" != "$HUMHUB_AUTH_BASIC_VERSION" ]; then
		ynh_safe_rm $install_dir/$HUMHUB_AUTH_BASIC_PATH
		install_sso
	fi
fi


#=================================================
# MIGRATE DATABASE
#=================================================
ynh_script_progression "Migrating database..."

chown -R $app $install_dir/

ynh_exec_as_app /usr/bin/php$php_version $install_dir/protected/yii migrate/up --includeModuleMigrations=1 --interactive=0

#=================================================
# UPDATE MODULES
#=================================================
ynh_script_progression "Updating modules..."

ynh_exec_as_app /usr/bin/php$php_version $install_dir/protected/yii module/update-all --interactive=0

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# UPGRADE CRONTAB
#=================================================
ynh_script_progression "Upgrading crontab..."

ynh_config_add --template="cron" --destination="/etc/cron.d/${app}"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
